# GitLab CI configuration file

default:
  image: "registry.code.syseleven.de/webcodex/x0/x0-test:latest"

stages:
  - build-docker
  - run-tests
  - build-docs
  - deploy-docs

docker-build-job:
  stage: build-docker
  script:
    - echo "Building latest docker images..."
    - sleep 1
    - echo "Built docker images successfully..."

doc-build-job:
  stage: build-docs
  script:
    - echo "Building Python Sphinx documentation (all versions)..."
    - sleep 1
    - echo "Python Sphinx documentation built successfully..."
  rules:
    - if: $CI_COMMIT_TAG != null

doc-deploy-job:
  stage: deploy-docs
  script:
    - echo "Deploying Sphinx documentation..."
    - sleep 1
    - echo "Python Sphinx documentation deployed successfully..."
  rules:
    - if: $CI_COMMIT_TAG != null

run-tests:
  stage: run-tests
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium-server-0
  script:
    - echo "Running app tests..."
    - sleep 1
    - echo "App tests completed successfully..."
