# GitLab CI configuration file

default:
  image: "registry.code.syseleven.de/webcodex/x0/x0-test:latest"

stages:
  - deploy
  - test
  - docs

integration-test-job:
  stage: test
  script:
    - echo "Running pytest3 integration tests..."
    - sleep 1

doc-build-job:
  stage: docs
  script:
    - echo "Building Python Sphinx documentation..."
    - sleep 1

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
