apiVersion: v1
kind: Secret
metadata:
  name: mypostgres-secret-${x0_NAMESPACE}
  namespace: ${x0_NAMESPACE}
type: Opaque
stringData:
  superUserPassword: ${x0_DB_SU_PASSWORD}
  replicationUserPassword: ${x0_DB_REPL_PASSWORD}
