apiVersion: v1
kind: Pod
metadata:
  name: selenium-server-${x0_SELENIUM_SERVER_INDEX}
  namespace: ${x0_NAMESPACE}
  labels:
    app: selenium-server
spec:
  serviceAccountName: ci-builder
  automountServiceAccountToken: false
  hostname: selenium-server-${x0_SELENIUM_SERVER_INDEX}
  containers:
  - name: selenium-server-container
    image: docker.io/${x0_SELENIUM_DOCKER_IMAGE}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 4444
  restartPolicy: Never
