#!/bin/sh

LOCAL_CONFIG="./deployment.cfg"
. ${LOCAL_CONFIG}

LOCAL_REPO_PATH="."

if [ ${SERVER_DEPLOYMENT} -eq 1 ]; then
	LOCAL_REPO_PATH="/tmp/x0_deployment"
	REMOTE_DEPLOYMENT_PATH="/var/www"
	DATABASE_USER="postgres"
fi

REMOTE_DEPLOYMENT_VHOSTS_PATH="${REMOTE_DEPLOYMENT_PATH}/vhosts"
REMOTE_DEPLOYMENT_VHOST_PATH="${REMOTE_DEPLOYMENT_VHOSTS_PATH}/${REMOTE_VHOST}"

LOCAL_DATABASE_PATH="${LOCAL_REPO_PATH}/database"
LOCAL_DATABASE_UPDATE_PATH="${LOCAL_DATABASE_PATH}/update"
LOCAL_PYTHON_PATH="${LOCAL_REPO_PATH}/python"
LOCAL_WWW_PATH="${LOCAL_REPO_PATH}/www"
LOCAL_WWW_PYTHON_PATH="${LOCAL_WWW_PATH}/python"
LOCAL_WWW_STATIC_PATH="${LOCAL_WWW_PATH}/static"
LOCAL_WWW_STATIC_SUBDIR_PATH="${LOCAL_WWW_STATIC_PATH}/subdirs"
LOCAL_WWW_X0_TEMPLATE_PATH="${LOCAL_WWW_PATH}/x0/template"

REMOTE_PYTHON_PATH="${REMOTE_DEPLOYMENT_PATH}/python"
REMOTE_WWW_PATH="${REMOTE_DEPLOYMENT_VHOST_PATH}"
REMOTE_WWW_PYTHON_PATH="${REMOTE_DEPLOYMENT_VHOST_PATH}/python"
REMOTE_WWW_STATIC_PATH="${REMOTE_DEPLOYMENT_VHOST_PATH}/static"

# SET BINARIES
BINARY_PSQL=$(which psql)

echo "Check Init Database is set:${INIT_DATABASE}"

# INIT DATABASE
if [ ${INIT_DATABASE} -eq 1 ]; then
	echo "Init Database is set. Processing DB scripts."
	for file in $(ls -1 ${LOCAL_DATABASE_PATH}/*.sql); do
		${BINARY_PSQL} -U ${DATABASE_USER} -h ${DATABASE_HOST} -d x0 -f ${file}
	done
fi

# UPDATE DATABASE
for file in $(ls -1 ${LOCAL_DATABASE_UPDATE_PATH}/*.sql); do
	echo "Updating Database."
	${BINARY_PSQL} -U ${DATABASE_USER} -h ${DATABASE_HOST} -d x0 -f ${file}
done

# CREATE REMOTE DIRS IF NOT EXIST
if [ ! -d  ${REMOTE_PYTHON_PATH} ]; then
	mkdir -p ${REMOTE_PYTHON_PATH}
fi

if [ ! -d  ${REMOTE_WWW_PYTHON_PATH} ]; then
	mkdir -p ${REMOTE_WWW_PYTHON_PATH}
fi

if [ ! -d  ${REMOTE_WWW_STATIC_PATH} ]; then
	mkdir -p ${REMOTE_WWW_STATIC_PATH}
fi

# COPY BASE FILES
cp ${LOCAL_PYTHON_PATH}/* ${REMOTE_PYTHON_PATH}/
cp ${LOCAL_WWW_PYTHON_PATH}/* ${REMOTE_WWW_PYTHON_PATH}/
cp ${LOCAL_WWW_STATIC_PATH}/* ${REMOTE_WWW_STATIC_PATH}/
cp ${LOCAL_WWW_X0_TEMPLATE_PATH}/* ${REMOTE_WWW_PATH}/
cp ${LOCAL_WWW_PATH}/*.js ${REMOTE_WWW_PATH}/

# COPY SUBDIR FILES
ls ${LOCAL_WWW_STATIC_SUBDIR_PATH} | while read dirname; do
	DST_DIR="${REMOTE_WWW_PATH}/$dirname"
	mkdir -p ${DST_DIR}
	cp ${LOCAL_WWW_STATIC_SUBDIR_PATH}/$dirname/* ${DST_DIR}/
	cp ${LOCAL_WWW_STATIC_PATH}/*.css ${DST_DIR}/
	cp ${LOCAL_WWW_STATIC_PATH}/*.map ${DST_DIR}/
done
