#!/bin/sh

#DEBHELPER#

if [ "$1" = "configure" ]; then

	# system vars
	WEBSERVERDIR="/var/www/vhosts"
	APPDIR="/${WEBSERVERDIR}/x0_js"
	PYTHONDIR="/${APPDIR}/python"
	CONFIGDIR="/${APPDIR}/static"

	WEBSERVERCONFDIR="/etc/apache2"
	VHOSTCONFIGFILE="vhost-x0.conf"

	BASEDIR="/var/lib/x0"

	DBNAME="x0"
	DBUSER="x0"

	# make postgres local unix domain socket connection trusted
	PGCONFFILE=$(find /etc/postgresql -name "pg_hba.conf")

	sed -i ${PGCONFFILE} -r -e 's/^local\s+all\s+postgres\s+peer$/local   all             postgres                                trust/g'

	# restart postgres
	service postgresql restart

	# check database x0 exists
	psql -l -U postgres | grep -q ${DBNAME}

	# if not exists, create database
	if [ $? -eq 1 ]; then
		psql -U postgres -f ${BASEDIR}/database/x0.DB.sql 
	fi

	# copy apache config
	cp ${BASEDIR}/conf/${VHOSTCONFIGFILE} ${WEBSERVERCONFDIR}/sites-available/
	cp ${BASEDIR}/conf/wsgi.conf ${WEBSERVERCONFDIR}/mods-available/

	# activate apache vhost
	ln -s ${WEBSERVERCONFDIR}/sites-available/${VHOSTCONFIGFILE} ${WEBSERVERCONFDIR}/sites-enabled/${VHOSTCONFIGFILE}

	# replace vhost domain from /etc in vhost config
	VHOSTDOMAIN=$(cat /etc/x0/domain.conf)
	sed -i ${WEBSERVERCONFDIR}/sites-available/${VHOSTCONFIGFILE} -r -e "s/^.+<SERVERNAME>$/	ServerName ${VHOSTDOMAIN}/g"

	# restart apache
	service apache2 restart

fi
