#!/bin/sh

#DEBHELPER#

if [ "$1" = "configure" ]; then

	# system vars
	BASEDIR="/var/lib/x0"

	# install psycopg2
	if [ "$(pip3 list | grep psycopg2 | cut -d ' ' -f1)" != "psycopg2" ]; then 
		pip3 install ${BASEDIR}/bin/psycopg2-2.9.3.tar.gz
	fi

	# patch psycopg2
	find /usr/local/lib -name "extensions.py" | while read line; do
		echo "Patching psycopg2 file:${line}"#
		cp ${BASEDIR}/bin/extensions.py ${line}
	done

	# restart apache
	service apache2 restart

fi
